apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgDQJ9mh02DPJUvmyTS3Clf6SD5atTy1qa5hTsQ/7ip6lFQjRAVFVLzmrbF1alm3EDXxGZe/CdQ20PGDlD5K53XShPMzvjebC+84g8DMBKIvFIJqLoKUpwxI3DSTkc8nBdDBVnGNj6DWWXnOmL78qibvX7XVmVIszQdOgmT4J7tTItIui6Z/7crQt+dW9BnDtEWjuTma+C0zlklCTm0+1Ev1NeW/UeOqN04bZcgh27Bp7PZwBJ9orVHhV0eQPH7g3VMmTaQx/cuItGjUGFrm9AAqR9BI8M9kJpSxFtSNBrh2I+uHdJrtziSTiiBMhPbCU1uModlapN6hR13oslGmFc6zUDHmjzTNlSFT0Zq64PCHvkKUy53j9YFIad7+0vDXXtB1SDrVJa1WkAfFR3mt6ejoZVhVYY/EpK9YQgP+juybkpjcdZTVp3Jw5bPlFlnPC1P+OrV8k/kgbLv2XqUKQAJUoQM/NLwE66DD7y8yp6/hvKl9dk2jHGvhFJNRZ09CzMr55dpRj3ydu4DXtr6jgKwdXolm/XSU+bDWglPnv6mnkz2+dh9SeAtQFKJXAS8IgsKgT5khsbmGGe7kjaMA6AGBasqvKCDMRMDnDL2GrGtYOLatOdKOVjWGY54fxojAJ7Q7Q8pOwhKw3pIGBeJer+9SVEZq+kK+jRoC2HvC70DomX5lyS7n6It457aIy/0DsILh2mVeSDk2hTFARQHx6uToICP7pdqbZlnM0I0jnazggJUQxgEZVvlEtvoP4xo7geqPrIhJE90ZXkRTXvg2Hh58Aq8qkd2X2WKareLfqGDp/XneVkqCZQ185Teqcov/RRV/xd5tJEN1RmcKoFPpdDHai9+LvLx7oW7k/xXkkcxynsG/BD6PW6Hu0HZMwrMPKZGOvNbjUy6ecfM6GcTvDu9/KIuvy3/RhOTaVYtYEtNPeXL4tSNNLPR2
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

