global:
  clusterName: qa
  kubernetes:
    version: v1.33.0
  kubeaid:
    repo: git@github.com:Archisman-Mridha/KubeAid.git
  kubeaidConfig:
    repo: git@github.com:Archisman-Mridha/kubeaid-config.git
  additionalUsers: 
    []
provider:
  hetzner: true

hetzner:
  mode: hybrid
  hcloud:
    zone: eu-central
    imageName: ubuntu-24.04
    sshKeyPairName: cluster-bootstrapper
  bareMetal:
    wipeDisks: false
    sshKeyPair:
      name: cluster-bootstrapper
    installImage:
      imagePath: /root/.oldroot/nfs/images/Ubuntu-2404-noble-amd64-base.tar.gz
      vg0:
        size: 80G
        rootVolumeSize: 50G

  controlPlane:
    regions: 
      - hel1

    
    hcloud: 
      machineType: cax11
      replicas: 3
      loadBalancer:
        enabled: true
        region: hel1

  nodeGroups:
    hcloud: 
      []

    bareMetal:
      - name: general
        bareMetalHosts: 
          - serverID: "2836489"
            wwns:
              - eui.002538bb31c600e5
              - eui.002538bb31c60104
          - serverID: "2836490"
            wwns:
              - eui.002538b531a43d51
              - eui.002538b531a43d50
          - serverID: "2836504"
            wwns:
              - eui.000000000000000100a075255218338c
              - eui.000000000000000100a07525521833ce
        diskLayoutSetupCommands: |
          set -e

          apt-get update -y
          apt install zfsutils-linux -y

          # Create necessary partitions.

          printf "d\n4\nw\n" | fdisk /dev/nvme0n1
          echo ",1K,L" | sfdisk -N 4 /dev/nvme0n1 --force --no-reread
          echo ",220G,L" | sfdisk -N 5 /dev/nvme0n1 --force --no-reread

          echo ",,L" | sfdisk -N 6 /dev/nvme0n1 --force --no-reread

          partprobe /dev/nvme0n1
          udevadm settle

          printf "d\n4\nw\n" | fdisk /dev/nvme1n1
          echo ",1K,L" | sfdisk -N 4 /dev/nvme1n1 --force --no-reread
          echo ",220G,L" | sfdisk -N 5 /dev/nvme1n1 --force --no-reread

          echo ",,L" | sfdisk -N 6 /dev/nvme1n1 --force --no-reread

          partprobe /dev/nvme1n1
          udevadm settle

          if zpool import -f primary >/dev/null 2>&1; then
            echo "Imported existing primary ZFS pool"
          else
            # Create the ZFS pool with mirroring enabled.
            zpool create primary mirror \
                  /dev/nvme0n1p5 \
                  /dev/nvme1n1p5 

            # Create the filesystem for ContainerD, to store container images.
            zfs create pool/containerd
            zfs set mountpoint=/var/lib/containerd pool/containerd

            # Create the filesystem where pod logs will be stored.
            zfs create pool/pod-logs
            zfs set mountpoint=/var/log/pods pool/pod-logs

            # Create the filesystem where pod ephemeral volumes will be stored.
            zfs create pool/pod-ephemeral-volumes
            zfs set mountpoint=/var/lib/kubelet/pods pool/pod-ephemeral-volumes

            # Enable weekly ZPool trimming for the ZPool.
            # So unused storage space will be reclaimed back, into the ZFS pool.
            # REFER : https://openzfs.github.io/openzfs-docs/man/master/8/zpool-trim.8.html.
            systemctl enable zfs-trim-weekly@rpool.timer --now
          fi
        labels: 
          node-role.kubernetes.io/general: ""
          node.cluster.x-k8s.io/nodegroup: general
        taints: 
          []
