apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster-archi
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgCCNa015S/oCCwRgBw1HMVeA3vQRKrXIWB+0YA5eWQn2MrzppPQysqOHTvkDQqp+S18Hc2J/BBEPyHY1KhQFAQCGCLxpXz+Ak1MGxJowNX0qboK+IVjb7631jrG3Cqc+i6g6FjHWIp9TgGJ6ImvjzvoL9s5QIHUQF8gpWbi8DTQkCQgq7il4GW6kLnZdxOJxklgkNANuq7gSNGoFb1IsiEHw0/KULfUo/lcp4C1S6pelPsXzbwN4nIag69D39wYYIWMsXG7HHWNFJclG4PSuNGKIhsQl2ZULUa7whBO0629j6gek3oxZBVnAbf4Jbd2Au6NEJorwqcqDNHcmZjIcr3I08Rfs6Sh5H1NjhCnjx/y/pAIf/nwxoH0e/QLh4rr4263PEFdKgHmLO42eVr9jpy8OFAtxC8hxfhOz42eKZgtr76bNw8bLSOIvAgHS/GpzK8L0fqaZBfQeKz7nV8mTdqAbZAJu1Lh1VEnoswp3RGgdIxjJViA1wh2GGignYeKmOnC5aJhdjdNzkCTL5mQOjT4Rq71/s0eQelZMUrWJw6z+sI9DoP17D4w2LqyjTig70gtmx2m8w6RiFl2KwHGEqy39UUN7JRkhNvRIHFXMvFWb7A5R0COB1qfHdBSGu+HQosORMc9wmkc67CA4VusI8Zj53QLtdmyt61NkQ+0TEo0b8jYnXREEvWWmtbmDAROvcY8+tlC09DyW+54655FtvpP+Orc0OXIeTKSXMg4eRL2hDiMc+xoN/dtBB/bCA9VhzAHqUImYaB5bo5S0XZKFsBgnQbWOmmPXat0/swQHklmsJLzLIzgKDNCe6cmixOSODlcGvrMEGIqqQoi0AJZTqp5rMMxx5vrasdhmrz50Ds6LYF9YtwhFTKuU6nkk90/z7MwQGedbeeVkAjCylB1Tq+/TBJ1culC9nHgFKpxXguvEOperA58Mvyl
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster-archi

