apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster-archi
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgBXiAhHLO3V4GZe+C+ZDKzqx4mg/Jn4scXdh/xqdjAXEEHQBjUuz0Fc312li3P55QSLIiraf1h78NZLeVtwRQ4270zxpA4iA8ayEBIObMspMtzYndm4Hn0Sq2HgIoLnUS+w+x2B6c8XdJum5XWfOlnygKdZ2S898ag5OD1P4NZfKYPDgRsBnZquycBwngec7QLXW60/xjQDsmmFAFGEi1wJXVCjwt84BLRY7nPN8v3nuv8aIDXlCQZ3CeQOqHg7aNlYZAG2oAaQzCURdnAgx2ebSNyEnUy3o05IH3BxAgs74oXe+E0z+HC46/tSzqRMIv7sEUQkjrU01noYKVO4tDGWpsJ78OZyz/B6bg485ydnCpxuKlL3/0uVf1QW5+CrodAyp5LkUOvIQRrwLqYKC41q7KJt4+Lj/qqY/OHj3GEemTTD23pNAkl5Dv6J+BbudOy9hAOJHtkv/nhgqp7zWpZ9miqg/UpH90PRUm4o5JtpyTA+9b74cRFFSkdFjGKJj02+J4ONrsiHOFqpbc+jw7A+zvcRW9Td5tFVffPb+QTgopqjVO5JgBa72eSS9B3Kvj9kQRE4piyXPo+21Qn9tClc8XWDemZmnWD+agX5P5LC0rfDnXbnvXCNlzMkWcU8F3YLos8HNOdgvOYgWp8Phk8gVWACvi5b+kiCvArV3iTBBHyc1ef43hJfuCZmSgd3TEPDnrCoBDH8/XWmArCtHZrbb/qCZfsk6pVn0sIeLKi4/mjpfzViZEAAN3x5q+zDu4pZQylciTaJyfwa6Ujj79oDLK6g/WY325cBeXUx5eJnHnBxQYJnWpSNB+EbWZ3D+rpdVwW3h5G4AV9LNx3aPMPtOtXJsJ11q4vz9V+y1wKCEtTXPcFur8SJK9F+ClO/SgLhsaaRTYUhrro0M2szmEHlO69gWwMVM+vTGU4i2GXBUJUXY8+7cThF
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster-archi

