apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster-archi
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgCS9NO0Gtx9zq8SFmWdTf3Ns+V3SSDarDmBoF/cAoM9w5+Vnj1lE76dMl2hEfMj1gzlY+aNAnyVpc9q+oUg74i/76Adw+DFl9H+iadyqwHdrlknCvoNIPpW36s8cNXNYEFKGB6VlavG/TVs5DH1glrcubejfc0dMJpMaunjcbecOylFyzd2I/FjtcZb81Af1LwiIm7+SWDatv1Y2mUdLPxd5HFmNL4LT22C6MV3p5AuAKFcUaH7Afg6zTua4TBbfCo/ElgTASqoP6vphWXkn6EovyqZNWfOhf+/Ww86kYBBqB3XFImX2SwieoR3sP5OIUhz+hksDZk7vWdn22K7bX3TX+nW49xRQ43aFLBvb6qDNZwnpfj6mK4BOcUOBsPmEut7dyUbjcDzyarsdO7IeHdT6u5J9MA70Tt34vop7G9ntB/Xo43Mp4ell80TwBZWQZozyiZpjd0WsX5ymRgSctyZiLjKNHB6IqndJv6u6T8aOOqPwrTYgOEoXA/q7Dx8hNA96c78/3PLLbm4Vq1TP0+sR/zAevremMZxykUcpl54NVZa3smvyTB23Dznp8aYEJMvq2IUhjIxJtSg+oBFBG5B/9A06kQm4Ig6p1R2Nscc3olyrg1aVCtiqi85qC+juyYZiOhNTlwLbPAG/aBJO/LaW+dRqLQCKzeO5/fMudqgxl2fCHE2bnYJlMXweNXwYWA6xS48cwJkWmU3BKuUjNwpTWxY9c/7vH1AgsOtlXOQ5XdVMppmyNYquqebZskNBu8ef8u0wk2VqALSC7XZ442sY88O9QnT61sBbiApO9lHUygaAzR8JNuvXBswRlzzAuChep+KdnZqxeXiz6oB5EjnKIh+0d3Gnesu76Q2wpm1//PhToTyWnB4XTzPnsUHuWZ8+RLjGbAe77/jqZaS0lbWXF9BlsQ4BeA4qbsNqO7dfWHwbVzeEX2n
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster-archi

