global:
  clusterName: test.cluster.com
  customerid: kubeaid-demo
  kubernetes:
    version: v1.31.0
  clusterAPI:
    version: v1.8.1
  capa:
    version: v2.6.1
    autoScaler: true
  kubeaid:
    repo: https://github.com/Obmondo/kubeaid.git
  kubeaidConfig:
    repo: https://github.com/Archisman-Mridha/kubeaid-config.git

provider:
  aws: true

aws:
  secretName: capi-cluster-token
  sshKeyName: kubeaid-demo
  region: us-east-2
  bastion:
    enabled: true
  vpc:
    cidrBlock: 10.14.0.0/22
  pods:
    cidrBlock: 10.244.0.0/16
  controlPlane:
    loadBalancerType: nlb
    region: us-east-2
    replicas: 1
    instanceType: t4g.medium
    ami:
      id: ami-0c5bfc0f41ac23871
  machinePools:
    - name: primary
      replicas: 1
      region: us-east-2
      instanceType: t4g.medium
      sshKeyName: kubeaid-demo
      ami:
        id: ami-0c5bfc0f41ac23871
