issuer:
  enabled: true
  issuerEmail: archismanmridha12345@gmail.com
  production: true
  secret: letsencrypt-key
  solvers:
    - type: dns
      cloudProvider: cloudflare
      cloudProviderSecret: cloudflare-credentials
      dnsNames:
        - projectsofarchi.xyz

wildcardCertificates:
  enabled: false
  # domains:
  #   - "*.projectsofarchi.xyz"
