apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgCgl7Dna/qCDRON0mMEdxvEjdRBH8oLWssuJxgH2LlqsLE44+qxS2Tzo9Itlog9e/JieAr0FP+g39QPMDBJ1HXZFmDUeOBcuV09krz9P6A52S0zP680XTeDvQjhX8kvtX5AQWVk/UPh3swpIssAedG5z4pqDF0RCt5fm0X8HCw8FhvRWIoN/TUYt3TkKDweWEr1khhjlb0j3RNSSr2BXLqvJmW0K/rzsNOa+zUWaDW4f9JJzUN5cNcDWwo/WMNW3XXihzJupbd27FYOa09/r35gZ8lHz1ek1RCI4R8w7VnlRydabS6YRZb4OXTpFi9q2+6xqfXl4DnjaSd0KKLg8viyl6BzfvKCbuvOVmFX30g6n8V0za91dYjC8HY9YAlgeWBwE0/Nf88Ywie1nKYqpsm3Bi1nrFQhQbT9DoINV9/abCE3/8WDAH3Gfs54X/4A7SuMNK6RqoMesG+kaYhPIhFnP0Pul0X9hlJMu42U49VpjSEzT+k23o7bpYnX5VgbFnqGvW2moL3snfEAz97MhUxYaqT4eOTt1ti2Txb7XxE4cuqUyGf2ciUvR8RYWEZd2OAyYAdMKld/SKJTh4qTHELcVV65XhxM7aP3aboiVrpqpTLMYEyUKcezjAYVEBZF0M2xZxS+R2r0t5pv3fe1FFeDeM1ZllK2sGoCQ19LECmSPbKkaaBNwZhkKrMjOYo6ebQtqgj1mJamxocgEPliJ/2ml9RqDzweJnuQnjg2smrpYdWEFxcmDISzz9azSrcgiNQctkLPXJPfxboV831XEndV1G+CnuhJeNmOBu0IfJfm+1tAz40dk07EKA5CU20p9Czdio0N3N1AIsdOxtBldB/i0DanSRxzxqU55j2vmETVaXCYv0VAN3qfS9hGDmyTuARzpWztN9GWPWPubxT6EYkW4kY351ibCkoOds0jjl6wSquHcm+Gwdt7
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

