apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgBJfjKWI2hdHbbAXMsxzOlFLsUs5hqM7bnl1XV//vVAZJo0h6LX3h2HvKxbbGx3o5zpcP/g8QrfMQNnVQtxBQl96nmqWzkEAPwRSfPn2NxIUjJiM38sSuqkGS3Nf5rwpLTsnzws4R6bxBncBZyOiaISL84ayLbqHcW6VTsIZWEMVMkF8hWoLNyQyP9lwDjHaMNZcJfiChGfq2dkfQLP0WH8RLiAqfKL2agu5dksc6pwByU2Npf9Wqm1fucmXI6PB7ZlX4PfiBXdjm4Q4/jlkaaqgQS32amLTbW6oXVRnr/5dC68pT3zmIgGBUFktJst1b8kRtkxIFzhz7sxP+ZD3BqxTIkbuzeRMJUtfsdoPjsiZ/cI3vguQQhT2tCKctn/8eljG5/0vwgjjyj3rgJ+g8r3aEcUc2hoyWuPim735whzEfmrH7cQJJONHE50BI4ISYAVIjOJVprl2jN6EQnASs4ixVtKFzRHN1STWFaIIoAOZQePlo0VnN1h/MXxH964pPRsPWBnN2VZNxY7U6qXU4YTYmsj0HQO/if/7out7itO/vU/PZ3fGf/AWZxEToSoja0glnWnCucSy1K2H7ewP80tGERQgk7Ey50KM6Yv4/Q2HIpD5LIXSSWfRdEXRJnWtwUIt0ACYwDjioZI9DSduyrQsxgMioBr5xeutm7dsO183n3/GdaL9AQoae6E8Cl439XDIi6Tv27k/A/zABDFvm1OWWdH9clzr/qFVVeMxrNxfigVhBZ/W13KErMg25MKGSE//TENFWL4ObQO0NXvmp9qABd4/4+ADKQmFxtjxogRv6b0bQx4N32X5DZawHXMMxUgiG1fo6bsfct/zM9dcwa9gUJ5zNpAawe/DCLL7NCM1CpEGznP7dyYx9hG2/gUd2g8zI4OQ7xbMl51p4MS2T8LeZiSfLkTtshHNuMH1J7oUjW8F+RR+rnD
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

