apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgB+73sMl2frCVPG2399Q6PgJoqO6eR1x66BOf4YWxvwKgnZnpN2QU+iv0uOH/pDlIHe5j2PDL+Ppa1/i81wJO00vZv3+B18rIV3z7ZCoSK50jeeo2/bgWQn8IU9b0EEuWJy/76YGYoRPtJGvgKY5VLFIAh/AI2T3gBhWiav3v35sFkgGmOzWZpUvP/cccvIowaYktrpg13kLWfSX+C6Zo3DJV6JkX/22DH51nMlrpRy9RV+RamTVNBrvooSAFr3+Ac+1/7Mnj0ZPYF36lj0lIrrL2VC9WW5mLBBw6YGkNxsoldKgQeGICEhwt/8cEvVVp0tRY8Jdue7lyfhTYOCCLlEM7BWO4UD53BtG0Tpbbzoq0n5ZdR0k84LIXJgGFWF8XpLw5LD6krN2B9Ig15uN/gxnrMKHNYO6qJVEM4MLpTB4tVAVSfWKZSQj5sSjMf9/SIBNz67lPorgzD2czwen5xgcU/4nfZQM03hNwf6tVXPeh6KwZn5uhAoxICRvF9VKWEkYezn7qOpgByYpPH70Rze6JBAoXccrU2kkTnebtvP8l5oDYZqFfQQolAqXKTrTw8AxYAfqb1NY8qcxCxVuUK+PrnYKkvWlZQYLcYlDvouoTLsFuGRU9k96iXZCVM7aB4icWqKexk0oSoUYWQ2ICq5Rg9nkLiS6QtAbezJIqzrorkPltJNzE98O1YljTgMtK+iSIBKvfSZPBMN+prcbb1y5oFhoStVp8LhqefWKLH8zHaNEymPZO1ou4kMZNdoJuD3NM1g2f2RmpWbHtoeds6kt1ZfggTS8j64/hVkPoNvyG5q6pO4QPUlV4Xw6cAd7FDBqxEM40aPSSCh5F6n9poSh5UkCjR/5DxwwLrRHgHc7DeVIsr0LkxPgUUewaf8y5Oi3QpM4IUfjaeO16jYLAHLYkVxajlkWyOKqXvUqO40trloQ9oSsmna
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

