apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgAhcUgvfzGy/St4rH2Pt7C1Q61mWc+e92U93p80G7UrmLgc28JXljXWy9YhyuUuwTZgO5SEvK7d4Ohvh9udqZzCd9r0RFhJy3RkxqpFbFrRvxwp8zNLJpAOq0+tBUIcSQe1nREax+zqOvg/TG3lM5yadgiODrAtY6yHlkHTl/2nRg6/vytV9HqxEMx6YsNaeyTMdNQ/Xte6IuO0CvNHa16aAwjzo++9Jv6qNBKQ7CeJCEeMIGMCJK3eUMLon+u0YyC53dCScebZmmbYcfgVUg87ronwxDtjGTIflQavBcbRUeVtA/scOtw49aPnqni2Ffmyy6+5qVf7j0DFZBexpfVIQVLPYb8cWcCHU10xZgErY9vpUHp03BswYYeOMEw1M2j0wBjKDgKTRosQoxqWkpp0S/dbm0n9Bi1t4OoezdmeDDt6oj2L9/tJX/LOoQdzo7i/MpiGOrL74VdnJXbRUzwFzobwdbouvi2muvfqkFd+U8kZp9VCp/WG0PgLk1jlFxDoBrAxbqJj3y+EuCbh+8xNJ5OS0OPCzWaxTybK3oV469B/3+tNU064f/rIJhB8qq2qUCwfslsnZIe4PkhzczO/gZige2+XhZGuOAl0Os/a92M5AocOfoIj7E5O3feNZC58Jq24+BsmY34+BAqCSYqcYf7J8XtYoJW6QYKBRA6OArO1T8TCV5+jFNRafW2Ni72WGgQrDAlp4inDthfirhkIDzOGz8PjgVjc/Oa8+XEb63wkoufSP/cWV2EMfrv2JSPIPtH2oGXfxybhD/BVe8B1bFQafqSJdXAUNj1ApObAuqB8bVKb+ZCcoIk8FuhrWQegz5luzqVMaL7GipouBynQ1U6VPO1slu+5nRGDpLqHYT9LHRa6biNNEIGiG+61zu/4N08HJTieXG0du/a1/29Ndja8GX+AlDYruk9yxSXqmrb64i9TcypZ
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

