apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgAZrEc0jAb0aCinJ0B4SXfRfAdVJvmClL+9UyvVDkyR9xgEhEgYg6UFax3VXOee32sOHlKv3GhQ7ivmcyt05l61OQCesO0e8tR7kQND3rK2c3tqc4C5j77HR2kT9ziYkCB8lMBDvmhcWwNxiK7MLJ8Ix2LfDpKAYxZjY6tONMMOBkbWCy7GkPNdvBE6D58XFDZTerzenwdAjRGau5WArDvJQL4LJisXmjBV1GUDdrVU04CtYhb3POHRAYr46kL+NtDHpjePwFEkRvcE/Q9fk6E6QT9uCIJmy4yj91bkRpJq/3Bmza/PmkCQWuuXVHKj93aYGi0wFa5hT/BQpUQPFSzOXHepPBjxh+2t2myA4vRrZU9rB4Rtun67oMK6Pi9tgrYGf8NlGPb8dg+sX8xWbqu+RF2Y0b2X8/XjJtSND1nWX6VjM8wDbxztIycV42IksngvS3r+BcFNTnQA5QDMVZ9mMMSWZro9d9YvKx555Q/i77wRBb1YyYZGU8EnqvcZsjI8+XlUt5bu8+HiNkgUBcfRev+30Ktq87fkTznCqPfXcx15r52+TkbUT0Ou0CllIs/HbIX/VUfkK+8SaNnLWNPN9LsxS2xyr+3gRXUOftLbZlkUhjN4donH4Qewc45giadU9mZ2xD2LW+nwg5juazYGw3r46CLE701WfejimpgTgzZjyeNG35eVM6ElMJwdurDQUPr6TLGpsytvPjyrcokTSxDkEsu/QwAWYWFVfuIhAe7EVLWhflWmVgkbzgYlSOpu+xvOgkc2o7flEsOGaDWnQU0Gentvt+60/YefLxldDcHjAUXsVbwvn2ydwFBNlpIBmWkgP6+WgYMbUrL5j1UZSWrNuAiJaYrMD/MCx1hYQINQApcZv7V14B8E9XQE2As8nXHCg/xU1IGzwdOrwM/MBTGuQS/fmr+hZdPxBNI/5+IGJgpcIl87
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

