---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAdpFdpLJU8qlAcl9XWj0+z2ZlgOA/GMkklyepkxAxlcoytaOSqgGoXRmRrH+S5y6i2r5Rz5O1Ui9vMFXQA+0ri41HgGehsJo4YjccOaFvWDVTfGhQouotwHjHzDIlcu0cjVaCA8I7furGri6/fj4dRQSYgdtZYI7IE7XOBD/ZSLA0hBqc/YDI3kDse5VqHnvnbrqT64x7ZU5sLh5HFJfo3CrKhvwvXIgkTGSwKOduaJSwWemuEL2PhXoMrtbQ1AEh6aLzX42U1jVVIua1hx2t90xiCxbXXXV+pkma+CQ60gu34gaDhEOEMcTplWo5v/FilYNLLTso4RPxEndRq5pnVz3oU3IyUDMV8Fe5hE0jTCGih3sQS3KUAHOKUVOiWhKrTvj23ypF6VZkQ9j5F060cYlUVg462F1QXf12B1iGbJEY8EngbpdAopmFtsGkP9RJ9LM/uhgtYQ1LWlLTG3aR7LZK720JIzQ1ukdLfcGx4IPKkszhU33CgwQ7w8ycs6ZGrMEuFzm97tF8iICRBjuA77dnzCE6STmOjx1J94bcv/v7FLZblvaycGRljrdqZcIqXngqpAoAsTORCYz1v5OK7eMJLhn5pY9TU76fFO5UMKcJ0Ty9DSGovM3xyJlerHOL75kHoFaI0qR+7THPwiA6m13aIrGj/QSx3Yj/AGuYK0IPGLVRTvbENrsd3UvXJ0cLuUBKyuRqSPmFYbwRt04rr4Jxl4JqhIjHwHR7HzoIDYHQy0wGkUZlwuJydROTgRT5hHFhtmbYT8kC+g34uJSfo
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
