---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBN9ZRa6UVdp1E53Tiohx88PUeC2PFQyolo1ckb2Pizg7NMZJyGf7w9Yah2MmDk/648tv8c/3aGLt87nb9MSLBBxH+i4INlr7CiDStughVLGIP5FTErEN1mBtl45A4pxfhhB8SidNv1vxiSSYpdvbwmZyLWHfsxAdDsupGcV8QjW0BT7LlujMjHRQyU5uFCA0iOaaHko+cFeZLmmiEVeFAqRubD1BbOJHkDjgdobKn3LMXFOWbuiJ//ctdJxq6mtrCu1AcUZcsItB+w+vB8kNR9gfAAsSxmNOLbTNezqbMVOWhp8ldVdVDD65PwXorX0stWqAEA6zqDd+BT1GrzLCPQkRpS2VaozriHo+tas4GQk20d8AoFp0RyCvX1EGdSjmvrrQ5vzXvtmHxiZ4E0T5X09NtQv0pW7BKkIe1tR1wkOZFqhW+Y76V/zOVpjymBYZ4y70mZcpXhf7Ab545iUq4wP36ANwkAp0z4jF750r3WYQxGE0MC7gHnXNodUkdACqMdYLehgaiYLFmDBgEo5OuVubpWrZGDX2nMNvFHmmqJK/v6+bsW/7TumVikCMrIE1hbdUlGC0V5rXsFSHXm/dfOLYA3eR4su+o/+mPEog722NUB/aVrRnd//AHNXIryEw6dfpPcqjd5mAIQp/guVI5RapHklZu4MNok4hVyWvoDS1E3eNn8Kn86wJeeYEBvo3tOrAPuGLhUnfsbo8qYH3/F6o8sGbR9/VouaCI7no4GnSlIDFnC4DRO1KvReEA6OxLep5UtSiCd5jRevfaof9M6
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
