---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBqyJaUgVWrbKD2lhiuiK3siH7hygBGuwgkL8jFQ3NqTPoDJJaflpcMiYHBLjHz+gUWU/HTar43k22eHCD1HVM1q32ol5syw0THKu777LOfjxODNyCShiWBvSphHiV13KlxQ75eSEj3Qe2jZDqsajChKyzItOz4Zus64Lege/im1S9qb8S1ja+Hnv1lEvhQxcR0a63wQmIHTFksphEnxw4G1/my8Tdpk9CmMiNTCWfdHWzvYRifPY4Q97e06794kCGcIJkk+mNO4A2mX7W+YwtLB5/s5muFHucDgxGaSXK4pX8KkLhU7KH18kwfLhDkwxSXemViAOBdY5cUO/Sfrnh7rZhTcMSkyZb0RDrnWFwKIhrPLkBpfHJgo+KT1UAKL7krEcRo9pKJjzO+/ps7zMXZnqFgrZlqFDK7G1+YYcNc70/kb+yss4p9bFb1Ufjus8wLsaTbR+Ax0+B1izyGrq8TkFYncPNq3r6jgXaGMV75+J/6YjqhrJxExo+a1RW1nzkktAl1GJvYMv9hTY5iTYnJa2LurrjCRV46LuussHydQtrHCnt5Q/Pds6U5pISIhtocVfSo6T4VPWEGXb50lbA/kSw+s9M7o6PbMOdmmEf69DrGn9+lOxgPMJE8v5QWjqdmhbac9k+5KSskA8KQk9XrmTHBSZG8G0NslCDSLToVjtKYEnLqGcrcxmB3L4tUbxwjGZFTz9QredZsQN816W8xj9Cwus3SWtuQedYxO7R2SMn3lh5bDIHamlQJxmjA4f3i5n/YCX8UU9MrAabtxCxC
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
