apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster-
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgCdX9fzw+VmP9tvzd07vpqRhIX18yU07n1zw5OI/LA8LjVNVPJVrozK4gF6cp5dxgzLizpbSgoOcOs8hTRLhupzWRJxtIZUim0m/z24SSJ8LYfqLJjE2UyKQx0jt2p3ECNhH9Ox48K7J7xZP3HF1eGGR7Oa1YnXs8m/9g4YJ1XClexcZBvcoPur8Ab6+gCIsCCuXDuP0jftx9zQYyJEBAJO8MOy2oOr6TkX/awH1laTEpjWeNZhdiRx5JGc0ahQYaiIEGl4vPk+/2uIMly/fIMQ6s3pULmHdQq0LRgCExyUyNH2ZEMmaR+YGkZzXF3wiMyrf//gIrVnMXUx+EMYL5oPRSwW/lwcS7ylRQV3k2QGhWhvEXY7PMl4igDCmCgwQfPjl1Bc1OOo0sE0+7HhG2xN7Y462Htitq9fFzwdcvbdy+GhnktXp7439hFy2QOdr6jIO6kjtvz2bwujBw6scUIC3PYfCAqQiV4jJyudm2ZDAj/C9AIVB5B914rIMfUmPSzQYJrGw1H26KvlzpqPqzmJKjQ5bZlXkwxl0dqIyHv8W994PsbacMD62QwQq08xMN3DNol3X5udqCnQh/hYr7rTUdOVo0wSrGGqhzUmpDPG5elXFq8ZePOguB7AZMR8BpOPpT7OOcjXuev7gJHQDViW5KpzxFU0cbMcMBPm4tbrUn3KQc7sgxgZcPWQebDBiBz/trwiQj+i7t7WfVL5TJq2n3xMfaTuo/p5xix3z2kRJtJYdu5Tq8FBGjVruh5pU4HDPJM6LVO5bv8op7mGhvwQz5QZxZJE/UcPh5Xaan8PM3ffTUqS01lFYhKb/NEaZS55bCYjxC90JfQS9DwHZ4VAxuEjYY2mr6L8zcC3aa0D2G2ZOi+Vr3DnMouc4P3+vupxAT4Am7ryv6VQ68QFk8XDfQHDyLdeGWAfl1NhjMGQ+KMUZPLBpLFX
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster-

