apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster-
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgApgfOKYefSICYGiNiNIPsAMNGHY04XhgYsoV8G3+kzFDD+Kp6hdVYgvLH1ZfKwZ4GOj2TofKCV2uOMhGBfnYsfFV82h9IfrUNHAAErg7GyM1xk+nFFI5z5TbXFp9kGxfPyj/Af6VYMMRGgaFYXxJgPpVCDoTvJZz79VzquD2O5yyaZPmAElExj/Dz9qoMd+UnrBr9lwHJNsOvvs1k/FTmL2BAMLPYWtyNA5oIb9ptvzwzvfBeXJNvr+fSQw0+s43L9Hbt0IOiO1wlTnwWu5Z9C0D4aapBdhAInIQsSTp2qXoTVkVzYDkpCjaGAWsT9PM9QO37U79VU41OUx8sc2tG2fS04Pc8c6EMc0CSlq6b+qJj45eVOsmSqwFB3KoZTmTgar16qOSZDHyWmKRyi+8XGYLvQhSuarmAlt9Dl3glpj9oX20rclQk6/9pqIHq94nZA3sfs/Hc7Do0slxoA2pjfnl1oHh+sOLj+4neT8p9ZMoUI2xx+tHu9B8zbFRrKz9ME9OmvtaVQLW5i3MG9Ung2HGbT5v8IwPm8xBagwcMTpdEG+po4SKROMG7q+L6NASTIfMBH4yXo/Std2xuTLVbJPs6KdCPqVmvrl1eIF2MLSPlukhh0OMKTv1F9apPz3QDANfdDhNgWVloEuWDonN9vEhrRHNiL6zMnUm0e4EV1p4KMZmTnDCCnYdx21VbP/yjy5FqDtW+Ih/qzTxDmBqVoZxww0ahJ5FBmG7n3qzIbxHnghWhlCRi8E3+YbQGl5rV3iS5We3UJyVdepByH7Xh+W5bKNM0jGcg5DsjnTTuZNqvyN6nwzk37mbibm5fiCWMC63B6Sj+wudqH1darBNiTW0c3DVC2w6ZDWCtD/yMItNKyZI4SgBYmwjF/wNi4Ml6zAlZyuwz75rREJWmaLbi0eTNQNnYV54b16WolQD94XP41BdVBm/eC
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster-

