apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster-
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgB+if36s8OicUSmRgx/4vWhmf0BV1tJTw1mB8SUMH7TQOqjuys2OPc+H7SANYZKAJVzy2UAdhCiseqtU3sZHwcy+L3a00RLwKv3Sv7RRoIMFeYJDZ1KU0QPoNgPvSdWs05hLILQYHlmI9dm6fzGaXIUBfIFzOzF7hRez739cFsmqgRSccUuqw2T2/3s7p4LyY17IFhfhiStWgvwQIlhGW5W87kKxF01MusSPw97TNLHjxxpKvuvib5Cegfhorx7A0x9JVho8InbSBf14f4EN2RgeoZZmAiXnwMQVog65+OBHTyaoGCyC+L3hVmAxaf4JmU3fePr6kGS6OiS75eta0mLpO7/IbVIMw+Rx58bixsGf6FzKUKsSd4heybV5kTxdv2hoZ5cGQZHCCFQUrnoj7yozRoHz0yFJB27A4hvrzANnBGR7dNTK5djP+d8p/0WIdwANVZC4nl4/h/oiS5RPPfNEDP1cyt53+E5wufXItoSX1XdFKw+80cKtBZ+4Rw1UKp1m5D92q/2TwiQTTI749k88EloHZk7bG/Rb5zuQAdk9ElfK1yKb0QWkskSccLQOlwliSaD1ZQWw2UGsovt4DvKWzH1oFYzszedVep+ZC2ULiJkLKNbBtfK3GK6kZF2n43ZnjTeaP2AmK91Fw0vCdxI8G0uvCB5542WcGQdMTOFrglyUHSzGFE+RMtcmGCHzAmZmtMd8Isv91/VGkRMcriFA4SzYnLnlzX0ufCWTn3agcZr+NBnV/098LQPj17A4BNDqTD476/WrOzRqpL2aAjPHO2Lt2smrZBmzdQEFC5GTCyd9j5bPMd32NVys8NvsPSmbtzOcuyWgMySi0dSA3/K6c2LyZtv4X+GyJ+TSOOBYL5xjRkQVi2KsDxr+AtyWBJL6MZF4WgkHm5DbAiiQPOzyVTkgFLPpDOGcM65PQ4EOCYsV3EgBNVY
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster-

