---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgBhNEA+4bpfNB1ijxx0yqIpETqQ4Xlt1qksNJ9MSg17bo3BX8zTflyNDs0lVt3fQ1epq+FlFxvPsXR+E/fm+WUC1/IHDLbu+K84D/1mYrX7Z/DRhqCzNf7fqIgK5y0oi0moEqMe6quWfa3OwxIKRHYurPFHZXZ7UH+rHdeKw51NEn7UN/wsvnJKk89cpo7Va3AsAreZR+WlO24hcg3UTD0ptI9rYN75dcHklRF+aXv3TeCcn3bnCFjTELkJG6KgfVMiv/No7Vz9pAqEupqvyOEdoTqAGUa1gCIwPqGfsHmxsiNerQSTCwxrDzJyGUtYPC8Bo91lyFxhAifqzZi7k8dKVH+JAP6sQlPNRXDBYQ8WnMQD3wG73rVAO1Q0lacVOafLol7harWUkyq0xomNqYv0/yHiQbzyEP2SQc/PF9PIUpexJqLjK3JWVvJkxsKGjA6syAl2fAl3clV1jFAxK/cYAdZDaeuWgCSKFNKua7xjnK+YH63PSRY/vtt2M7BbFH6Ha2lhOvq/62e4FzaEz+zuWE8D31PWlhLhF2iKYmkRaGeewR7pnKHluYoG1QsiBWG7fkwXDmK0cgHc79F4KI7PXEaQr9+AV7UPh+0X9kODm8twgqF0Ovi8Mi10qLHCuBj/4J8ryS13w0sIvwyJr+OlSJlp0jktmkc9ameI3Kfo7/jjHP3pwFOk4yoKc6734s6CHFlllNGFKQOoaKYdY3SsSVZY6JWjWBlp5h9yBwmKZnfM+nfLp127jjJ1HoAVloKGsgKmM+X9aqbGmgYH53mAWgtd18C3D6714VX5vhEHcSPmX0ZJ97+VvD0QbLV3YQdqP8Loe0dnklz5MIsOcj2NwZo0MumqtbM8AXZEgOfsxhP3K7jPFpOeM5wBrytWgp3cQKCZK079P5gV2pBHHH/emdvfnFHRmus3XHe4N8HomYFQQbtg8hbo
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
