---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgCZ1FjfYQz46/BLkSg+/W/LKjlH9L+IyqQMXEcBg7UjxXwjRekPpwZc3nUmKomTeSQke4piyNIbke5qrv9N8XtxTt7hEDvtgi+CLiDp1x+EfYZbF4IrIHfXOBRfba4rbUbIy6RVRyDaelemH/m1tBrH880Zo2AuhBXLK8bMb0caczVIt12G0NbGZtIS04UdHeutJc2ZI0fE+v/Ryqm7CRtUVwK+025BOt5Y5SrQ9O72SxrFvK/FoA7Ybo9naO1+tP0tRNRiMvoLVAmn919VMOk3XnpdkhRmbkzMZE/aME+f0Js1srscqdGA+V1WPNGFDD1BkIpiWO9sjSmhqedIGXlnteWd6I5VJ60MSR+WaEYEIqt0SsOHbY+rghEa+4Ys4KuuSOVGuiEzVPkor3v5xpsvhCYcwcqCpUKidu5h/O1bq6LJ0q3L5EyJchA6N0F8nfeaNin/iPbB2zhCKCJp+34NFBoOw0pyEYvHi+NX72DZii9FGvfj5nWvbiKy0AiZKqqsiYsXR5eiGZ28buqG4in9bWABMdO38MBihT2GFmcPk6DFlt7Z7lP5DV/9uzTo1Soc8QMPy9Iw0IOotIskl/cNAHFK/70IhrtPzeb/Qx2fmOVeQwc2fTtCOv9+eBETq3kiW1Du4yCvgsS1pjM5DGVTMvyxYx/VBYVBQO74ntDJia0J+/8kBDxAbEXD0WK3pA+xfKlXC0L3SSFH/AwfqDpR5ezZHwPXaGVt3Gs3D5f2Q9SW0tpC1nE/0RNWbisg4aIBjZJUsk+D+ms9iN+JuscSRQl38KsDDOg6SlcWbUwTj/9lDLm08qNX1EIX53WpuoeiBjb5kaacwCK854q2mR+xuKNRhaP+0/ODiHUgvpKnHhqnIREbpWC7Q6XliP4DaVuFxBM0kP3jWRKYebYfuWdL58ZAQqvIKyRnET/eRI116S7Vj+tWZA8N
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
