---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgANoX00Qfb809F5GM+7uFMuTvYgkeBB+l/JL7MFDF2AS/RKxfid5EDxxqgSl2ADsLnr9Bzkw+3KsSAAxl0B/SYuNBDT9kqp5Cm4rnQIscgUi4NMqGhDwDj3dPOoeZXgOA27R3bze26jLKJa1KJcyaUWkhVjPxnJNv1fGHLCkIe55tfCh2VbuZ4j1qaLriqNvbVuaCc7N/DA81nofeUQvSBfW37MHA4+AF/pZ3PNj8ZzzdfwZtT2BZbSpPPuYVtXeif/3eQp25P6mtVT53QhLEbUfP0k0IwU2cylHpzJTgC2yVSHoEH1KbU8brTa4QrOQhqM7hn0PUp0MH5hk8gU5CRzVfG6A7N9DcPMlbAuMT1LjRt+C3gWyi35BpCa/ebwJ5MUtLWp80V4iGf80k44Fq/ArNeb2GZDxHDiunWz7x2nsyed4olzms9IHfxmQL86YfQFG7xtFKNyDP+9dTrIVRAz+Ie7VKXzTCLnTD9l3UYk1J1TEPgmLc92kzAmgcQCPrWeLdOt1sJDaJwDhd+EtZOmEquf4ZGEzMNj6F3uwHNxaD8pSpGExchuxwtbSCUn0Wykf/2QiRptK9wzjq2ixlj6vR9x13MELrKjq8y8K+lyEk/ku0i+DqOO18cggCKyV0TKFkRFqBAv1TTHNnSdY7cyOtq3oRtFi0inCpNGPqInPZCpBPHQGJIrOA1h4j3UGceLl2niJ8KJXfRqNGDQNPfjzx0RDpNbpMnRxFIUQiDw0SR6vLCgvnogYU10jKruUa7VgdchiTqcAvwoQCWrqSg6tFd8nwAhSQ42K3j4QazT866JRw7T8eIbPb8LF0HM6qCtHADMGQAwdQq/KCFqsF5hMEECZdIRE4G5NMIqiDHYIs7H0cGJJos1TuAkysixXLduvoG0OC0YeSELFp6ApuFWq7zsq/OPgXzC/hm07ODyHBFdcFKvXI5h
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
