---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgA/Ns6FvoXWSW4f7aYr9wlSStpqK60sZASgpBEOVtHwPo+6lAfYoqzCh78ZJEI79i+oGNaireN8MByirUnpSlok42yXuFwFscyeSu+cAUczfNyI8U4Dq/EUyh49/NBuTMnUW7D2miwvnwa4jpqmoxnPulihVbWzlZV2wO48TMXDdyqsZFbIkHsaEu4F7EjaNB3snDH2Vc5SYiPKoTkVi6of1YMdFM6/dfUuy+xO2zoPrkPHIHwI/mkEsFMdnmFLv5Hn2e4Gprr2nP35IIKZo9is6fIz7fJi6NbNDyDPu007O302CbihGIBednBxjVMAPIhrd41KkFQuux0t9heClqfT3TeO2ea3U3Cg4f4KToDOdZ9gD/04dnyxqHyq99ooqmAkGlvQVCwpyKw7v1O5QgZwYUA0MJDmt1NlnuIFnuyh/EKJHGM46RHgf16rricFg2vgItdwwrvrbs1fkduTj9K4xSvycH5d+9b4L4A42TTi13nrhJfAcVg9bqUBa7ghXA3nFT1768nrH9ipGShSPpq+BBOZMAFobqn3fW3jz2HJU2DGwLpNhiCF9/hepRyxqUnp7JbQCnmfuM9PtA0zjAwHk294uLE73Q30TTqgdlfAMhOOosECmx4mqE4gLkWM7QXUuO8YpdeInu1FcJ0vAuafrVgJqjsCpOgFN5Spy7WaClIzrrKum7y7A08eS1Fk1q5ZG2WmysLV8s2cSf+jPvU5aT7VH9Xki2sO0XyUpyZ8lkxeRq3lDDMNwd+kSNUAwm7EJ/CT8Xx/Svs0SjXFQCGD
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
