---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBO4mJtKLnM+ChnBSnc6icU6tdjxaWBGzd9VpwYdN8jKa4/q1r06CqebsSd8Mp231hhdRUppB+/TsPKgOVmDkSjBsi1GZptMwjMmjItYmyS7OaXZ71yRTEv1Qm+RrJOLoJel0OkMaH/ZOtf/ZW3GykqcdKslhWrN1sbR8rcdtQeCPcYoJqEAHyeXnX5kBqwxR2tVesVmlh9a4qCSN8060DO9WhDSyl+T3Rv/UBOWG1+BM54BkGph79HgzoupIUozERdIcrrLCq3XkBbzWSPMdN392Lbh8yD2VmjeOChdPPsI2G3gKyHnpqYlKKxSCwVnB7N5I6RZsdv8Rn+6N7FAan9D6VR3fzckP97EOoIq7PTBv8Ac+Qkp2MxPiOl9E6VXiqeywqKwJxV9CrdtRwaCqUy4tWSd82PYAMASFCPF8HxPujztIDWfDcKLiroeoRjtyNUJKJCucFS0uCK/8N6/WJUTCgBfqqsd8Yx1Zw22540dXllA7KnCCGWUQgyjyq863W+eA51FldrZS9fg4rWEFNx47jKRBavQwiXyRZ8Fz491Bcve8x7fl8DeSDKsWtD+A1cgK6yznP5IORQg6F6ntgyaRkN/qitR68wHk0pp9XcvNaUSaYB9FUT7MqmN6jsjX7lbZmf3N+uUombgTAUbKxiuXvK6BRG5RjmJPjR/pUrBJQBIrYyf69AF0X9vb+gHC7M7OVob/4D1hTMPaKHTHUjZcUf5Uky6agoA1G/RnwQXnAmViP3P3r933uRMXag5mWJ4DLvlnAomzg0Fi6+WY6X
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
