---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB0gUHglxWYygdPwAE7i93FdMHApXbYSY4S47dmyq8F6hRvLaowK9M85Jwd0wh33gs2rHgnNkA5I+nvCypk6nvrSl+QXF6fzZb6eFUCpMY+wKEIiICBH9wPU75RQCGu3+js3k5VoEj8LThc9fAyGg4m+cPBkLEBq2+cWHo2eOGbNs2OkqnH4vEcueP9FiJAEV4IRov/nabeYu4FswmPz6rNwesnFMPGaR7D/g+RIwWvVgN3vQnfy5DMkdlB25vLovuGZ8Zj0MX6FhhecIMbFIMaE7Zu2FWNYJ+Qh1ELSV5fsqXrTceB201jo1KojH8PAEAtpDiMW8MQZ8NXQH/0Us/Rslv4NEVG7z1hlaPJEWarzeDDH6LwiLj9IbvJ0ptwYmhxovbMCINIMkQXSH4y9GfHzsyYTelOPmvwQ8IckawiSs1ohPw57BxjNwOKH9J2e/ienJfKS1HyIMRvQ+tMjRe5xgrQ9ND4zjWfCopPRSb3zDAI+pUMyEf3lHXNJ7tGFsjEv96wzXSNot0GJAO9mXq+tGhCvWfL/zHwza0bEDlovJciQhoF1PA2+yPSSXZsDcuIl3dFqOvFlk+qmm3ilrftOWuFiruL0meD7V55FJmN0w/7XVsJsQDPzTB8vsAXHWJje4btRHU+I8bfNZTOxJesSo+u4VfT6bivVUFBjQkhf1dLF1ZG84uja6ROPlD0NQ04CDNG7jlMiXn6gPodCY+8uOM8jpTZUSNnNZbxGP66a7vJxzc7P7GrUsHg59DmXw1WO6JhPQZgFA9bwkKRNrGK
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
