global:
  clusterName: kubeaid-demo
  customerid: archi
  kubernetes:
    version: v1.28.0
  clusterAPI:
    version: v1.8.1
  capa:
    version: v2.6.1
    autoScaler: true
  kubeaid:
    repo: https://github.com/Archisman-Mridha/KubeAid
  kubeaidConfig:
    repo: https://github.com/Archisman-Mridha/kubeaid-config

provider:
  aws: true

aws:
  secretName: cloud-credentials
  sshKeyName: kubeaid-demo
  region: us-east-2
  bastion:
    enabled: true
  vpc:
    cidrBlock: 10.14.0.0/22
  pods:
    cidrBlock: 10.244.0.0/16
  controlPlane:
    loadBalancerType: nlb
    region: us-east-2
    replicas: 1
    instanceType: t2.medium
    ami:
      id: ami-0b633dfdc16bd31ce
  machinePools:
    - name: default
      replicas: 1
      region: us-east-2
      instanceType: t2.medium
      sshKeyName: kubeaid-demo
      ami:
        id: ami-0b633dfdc16bd31ce
      labels:
        workload-type: monitoring
      taints:
        - key: workload-type
          value: data-analysis
          effect: NoSchedule
